resource_group_name        = "rg-market-data-dev"
location                   = "East US"
databricks_workspace_name  = "dbw-market-data-dev"
storage_account_name         ="scmarketdatadev"
access_connector_name      ="ac-market-data-dev"