CREATE SCHEMA IF NOT EXISTS bronze.processrunlogs;

CREATE TABLE IF NOT EXISTS bronze.processrunlogs.DELTALAKEHOUSE_PROCESS_RUNS (
    PROCESS_NAME              STRING,
    PROCESSED_FILE_TABLE_DATE DATE,
    PROCESS_STATUS            STRING,
    RUN_TIMESTAMP             TIMESTAMP
)
USING DELTA;